# Generated by Django 3.1.6 on 2021-02-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=70)),
                ('title', models.CharField(default='', max_length=70)),
                ('images', models.CharField(default='', max_length=70)),
                ('productCategory', models.CharField(default='', max_length=70)),
                ('colors', models.CharField(default='', max_length=70)),
                ('prices', models.CharField(default='', max_length=70)),
                ('discount', models.BooleanField(default=False)),
            ],
        ),
    ]
